{{- if .Values.serviceAccount.create -}}
{{- range $serviceName, $service := .Values.services }}
{{- if $service.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "media-center.serviceAccountName" (dict "root" $ "serviceName" $serviceName) }}
  labels:
    {{- include "media-center.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $.Values.serviceAccount.automount }}
---
{{- end }}
{{- end }}
{{- end }}
