version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    labels:
      - type:chore
      - area:devops
      - component:infra

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Etc/UTC
    labels:
      - type:chore
      - area:devops
      - component:infra
