"""Content Generator & Link Router service package."""

from cglr.link_rotator import (
    DEFAULT_L3_MIN_CONTRIBUTION_WEIGHT,
    REFERRAL_REWARD_RATES,
    InMemoryReferralClickTracker,
    LinkRotationError,
    LinkRotatorError,
    LinkRouteRequest,
    LinkRouteResult,
    ReferralClickStats,
    ReferralLevel,
    ReferralLink,
    ReferralLinkTarget,
    generate_referral_links,
    select_l3_partner,
)
from cglr.template_engine import (
    DEFAULT_MAX_CONTENT_LENGTH,
    TemplateEngine,
    TemplateEngineError,
    TemplateRenderError,
    TemplateRenderRequest,
    TemplateRenderResult,
    TemplateSecurityError,
    TemplateValidationError,
    TemplateValidationRules,
    render_template,
)

__all__ = [
    "DEFAULT_L3_MIN_CONTRIBUTION_WEIGHT",
    "DEFAULT_MAX_CONTENT_LENGTH",
    "InMemoryReferralClickTracker",
    "LinkRouteRequest",
    "LinkRouteResult",
    "LinkRotationError",
    "LinkRotatorError",
    "REFERRAL_REWARD_RATES",
    "ReferralClickStats",
    "ReferralLevel",
    "ReferralLink",
    "ReferralLinkTarget",
    "TemplateEngine",
    "TemplateEngineError",
    "TemplateRenderError",
    "TemplateRenderRequest",
    "TemplateRenderResult",
    "TemplateSecurityError",
    "TemplateValidationError",
    "TemplateValidationRules",
    "generate_referral_links",
    "render_template",
    "select_l3_partner",
]
