name: "🐞 Дефект"
description: "Сообщить об ошибке"
title: "[Баг] "
labels: ["type:bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Описание дефекта
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Шаги воспроизведения
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Ожидаемое поведение
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Фактическое поведение
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Окружение
      description: Версия, сервис, тенант (без ПДн), логи (без секретов).
  - type: dropdown
    id: priority
    attributes:
      label: Приоритет
      options:
        - "critical"
        - "high"
        - "medium"
        - "low"
    validations:
      required: true
