from __future__ import annotations

from messenger_adapter.base_adapter import (
    MESSENGER_ADAPTER_SCHEMA_VERSION,
    MESSENGER_ADAPTER_SOURCE,
    PUBLICATION_FAILED_EVENT,
    PUBLICATION_SUCCEEDED_EVENT,
    BasePlatformAdapter,
    EncryptedPlatformToken,
    InMemoryPlatformPublisher,
    InMemoryPlatformTokenStore,
    PlatformPublicationError,
    PlatformPublishCommand,
    PlatformPublisher,
    PlatformPublishResult,
    PlatformTokenCipher,
    PlatformTokenCryptoError,
    PlatformTokenNotFoundError,
    PlatformTokenRepository,
    PublicationReceipt,
    PublicationRequest,
    ReferralLinkRequestTransformer,
    RetryPolicy,
)
from messenger_adapter.content_transformer import (
    DEFAULT_PLATFORM_LIMITS,
    PlatformContentLimits,
    PlatformContentTransformer,
    TransformedContent,
    limit_media_items,
    media_items_from_metadata,
    smart_truncate,
)
from messenger_adapter.dzen_adapter import DzenPostPublisher
from messenger_adapter.ok_adapter import OKMediatopicPublisher
from messenger_adapter.platform_registry import (
    InMemoryPlatformRegistry,
    PlatformKey,
    PlatformNotRegisteredError,
    PlatformRegistry,
    PlatformRegistryEntry,
    PlatformRegistryError,
    PlatformStatus,
)
from messenger_adapter.referral_links import (
    REFERRAL_LINKS_METADATA_KEY,
    REFERRAL_ROUTE_METADATA_KEY,
    ReferralLinkGenerator,
    ReferralLinkInjectionError,
    ReferralLinkInjector,
    content_with_referral_links,
)
from messenger_adapter.telegram_adapter import TelegramBotApiPublisher
from messenger_adapter.unified_adapter import (
    PublicationBatchFailure,
    PublicationBatchRequest,
    PublicationBatchResult,
    UnifiedMessengerAdapter,
    UnifiedMessengerAdapterError,
)
from messenger_adapter.vk_adapter import VKWallPublisher

__all__ = [
    "DEFAULT_PLATFORM_LIMITS",
    "MESSENGER_ADAPTER_SCHEMA_VERSION",
    "MESSENGER_ADAPTER_SOURCE",
    "PUBLICATION_FAILED_EVENT",
    "PUBLICATION_SUCCEEDED_EVENT",
    "BasePlatformAdapter",
    "DzenPostPublisher",
    "EncryptedPlatformToken",
    "InMemoryPlatformPublisher",
    "InMemoryPlatformRegistry",
    "InMemoryPlatformTokenStore",
    "OKMediatopicPublisher",
    "PublicationBatchFailure",
    "PublicationBatchRequest",
    "PublicationBatchResult",
    "PlatformContentLimits",
    "PlatformContentTransformer",
    "PlatformKey",
    "PlatformNotRegisteredError",
    "PlatformPublicationError",
    "PlatformPublisher",
    "PlatformPublishCommand",
    "PlatformPublishResult",
    "PlatformRegistry",
    "PlatformRegistryEntry",
    "PlatformRegistryError",
    "PlatformStatus",
    "PlatformTokenCipher",
    "PlatformTokenCryptoError",
    "PlatformTokenNotFoundError",
    "PlatformTokenRepository",
    "PublicationReceipt",
    "PublicationRequest",
    "REFERRAL_LINKS_METADATA_KEY",
    "REFERRAL_ROUTE_METADATA_KEY",
    "ReferralLinkGenerator",
    "ReferralLinkInjectionError",
    "ReferralLinkInjector",
    "ReferralLinkRequestTransformer",
    "RetryPolicy",
    "TelegramBotApiPublisher",
    "TransformedContent",
    "VKWallPublisher",
    "UnifiedMessengerAdapter",
    "UnifiedMessengerAdapterError",
    "content_with_referral_links",
    "limit_media_items",
    "media_items_from_metadata",
    "smart_truncate",
]
