"""Shared tenant-isolation primitives for Media Center services."""

from importlib import import_module
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from libs.shared.audit_logger import (
        AUDIT_HASH_ALGORITHM,
        AuditLogger,
        AuditLogRecord,
        AuditLogSink,
        AuditPayload,
        InMemoryAuditLogSink,
        audit_hash,
        audit_hash_from_payload,
        build_audit_payload,
        canonical_audit_json,
    )
    from libs.shared.auth import (
        AuthTokenService,
        InMemoryRefreshTokenStore,
        RefreshTokenRecord,
        RefreshTokenStore,
        TokenPair,
        TOTPService,
        TwoFactorConfirmation,
        hash_refresh_token,
    )
    from libs.shared.cache import (
        REDIS_URL_ENV,
        CacheSettings,
        InMemoryTenantCache,
        RedisTenantCache,
        TenantCache,
        build_tenant_cache_key,
        redis_url_from_env,
        validate_redis_url,
    )
    from libs.shared.config import (
        APP_SETTINGS_ENV_NAMES,
        REDACTED_SECRET,
        SECRET_ENV_NAMES,
        VAULT_ENV_NAMES,
        AppSettings,
        EnvSecretProvider,
        SecretProvider,
        VaultSecretProvider,
        VaultSettings,
        load_app_settings,
    )
    from libs.shared.db import (
        DATABASE_URL_ENV,
        NAMING_CONVENTION,
        POSTGRESQL_ASYNCPG_DRIVER,
        AddSession,
        AsyncDatabase,
        AsyncScalarSession,
        Base,
        Contribution,
        DatabaseSettings,
        PayoutDistribution,
        ScalarRows,
        Tenant,
        TenantOwnedMixin,
        TenantScopedSQLAlchemyRepository,
        TenantSetting,
        TenantWeight,
        WalletOperation,
        create_async_engine_from_url,
        create_async_session_factory,
        database_url_from_env,
        validate_database_url,
    )
    from libs.shared.errors import (
        IDEMPOTENCY_CONFLICT_CODE,
        POLICY_GATE_REQUIRED_CODE,
        RATE_LIMITED_CODE,
        SERVICE_NOT_FOUND_CODE,
        TENANT_ISOLATION_CODE,
        UNAUTHORIZED_CODE,
        VALIDATION_ERROR_CODE,
        ErrorBody,
        ErrorCode,
        ErrorEnvelope,
        SharedError,
        error_response_body,
    )
    from libs.shared.events import (
        DEFAULT_COMMANDS_EXCHANGE,
        DEFAULT_DEAD_LETTER_EXCHANGE,
        DEFAULT_EVENTS_EXCHANGE,
        RABBITMQ_URL_ENV,
        EventEnvelope,
        EventIdempotencyStore,
        EventPublisher,
        IdempotentEventProcessor,
        InMemoryEventBus,
        InMemoryEventIdempotencyStore,
        PublishedEvent,
        RabbitMQEventBus,
        RabbitMQSettings,
        event_routing_key,
        rabbitmq_url_from_env,
        topic_matches,
        validate_rabbitmq_url,
    )
    from libs.shared.gateway import (
        APIGatewayASGIMiddleware,
        GatewayRoute,
        GatewayRouteNotFoundError,
        InMemoryRateLimiter,
        RateLimitDecision,
        RateLimitedError,
        RateLimiter,
        RateLimitPolicy,
    )
    from libs.shared.load_testing import (
        AsyncLoadOperation,
        LoadOperation,
        LoadScenarioResult,
        LoadTarget,
        LoadTargetEvaluation,
        LoadTestReport,
        evaluate_load_target,
        run_and_evaluate_load_scenario,
        run_async_and_evaluate_load_scenario,
        run_async_load_scenario,
        run_load_scenario,
        run_threaded_and_evaluate_load_scenario,
        run_threaded_load_scenario,
    )
    from libs.shared.logging_config import (
        JsonLogFormatter,
        normalize_log_level,
        setup_logging,
    )
    from libs.shared.models import (
        AUDIT_HASH_PATTERN_TEXT,
        EVENT_TYPE_PATTERN_TEXT,
        TENANT_ID_PATTERN_TEXT,
        TOKEN_PATTERN_TEXT,
        AuditHash,
        AuditHashReference,
        CorrelationId,
        EventType,
        IdempotencyKey,
        JSONValue,
        PagedResponse,
        PageMeta,
        PaginationParams,
        RequestContextModel,
        RoleName,
        SharedBaseModel,
        SubjectId,
        TenantId,
        TenantScopedModel,
    )
    from libs.shared.object_storage import (
        DEFAULT_PRESIGNED_EXPIRES_SECONDS,
        DEFAULT_S3_REGION,
        DEFAULT_S3_TENANT_PREFIX,
        S3_ACCESS_KEY_ENV,
        S3_BUCKET_ENV,
        S3_ENDPOINT_URL_ENV,
        S3_REGION_ENV,
        S3_SECRET_KEY_ENV,
        InMemoryTenantObjectStorage,
        ObjectMetadata,
        S3Settings,
        S3TenantObjectStorage,
        TenantObject,
        TenantObjectReference,
        TenantObjectStorage,
        build_tenant_object_key,
        build_tenant_object_prefix,
        build_tenant_s3_prefix_policy,
        s3_endpoint_url_from_env,
        validate_s3_bucket_name,
        validate_s3_endpoint_url,
    )
    from libs.shared.observability import (
        DEFAULT_METRICS_PATH,
        OPERATION_COUNTER,
        OPERATION_DURATION,
        ObservabilityContext,
        ObservabilityPrivacyError,
        TenantMetricRegistry,
        TenantSpan,
        TenantTracer,
        TraceContext,
        build_structured_log_entry,
        format_structured_log,
        observability_context_from_tenant_context,
        sanitize_observability_payload,
    )
    from libs.shared.rbac import (
        AUDIENCE_ROLE,
        BLOCKCHAIN_AUDIT_ENDPOINT_POLICIES,
        BOARD_ROLE,
        COUNCIL_ROLE,
        FORBIDDEN_CODE,
        GOVERNANCE_ROLES,
        MEMBER_ASSOC_ROLE,
        MEMBER_FULL_ROLE,
        PRESIDIUM_ROLE,
        AccessPolicy,
        EndpointAccessPolicy,
        ForbiddenError,
        RBACASGIMiddleware,
        require_access,
        require_any_role,
    )
    from libs.shared.resilience import (
        CircuitBreakerPolicy,
        CircuitBreakerSnapshot,
        CircuitBreakerState,
        DependencyCallResult,
        DependencyCallStatus,
        DependencyFailure,
        DependencyKind,
        DependencyResilienceGuard,
        FailureMode,
        RetryPolicy,
        TimeoutBudget,
        constant_fallback,
    )
    from libs.shared.s2s_auth import (
        DEFAULT_S2S_REPLAY_WINDOW_SECONDS,
        S2S_SHARED_SECRET_ENV,
        AuthMethod,
        InMemoryS2SReplayCache,
        K8sS2SAuth,
        K8sTokenReviewResult,
        OIDCK8sTokenValidator,
        RSAS2SAuth,
        S2SAuthenticationError,
        S2SAuthenticator,
        S2SConfig,
        S2SIdentity,
        SharedSecretS2SAuth,
        TokenReviewK8sTokenValidator,
        detect_auth_method,
        get_s2s_auth,
        require_s2s,
    )
    from libs.shared.server import (
        BASE_APP_LOG_LEVELS,
        BASE_APP_SYSTEM_PUBLIC_PATHS,
        DEFAULT_BASE_APP_DOCS_URL,
        DEFAULT_BASE_APP_LOG_LEVEL,
        DEFAULT_BASE_APP_OPENAPI_URL,
        DEFAULT_BASE_APP_PORT,
        DEFAULT_BASE_APP_REDOC_URL,
        DEFAULT_BUILD_INFO_PATH,
        DEFAULT_RUNTIME_APP_HOST,
        BaseAppConfig,
        BaseAppState,
        build_runtime_app_host,
        build_runtime_base_app_config,
        create_base_app,
        create_service_runtime_app,
    )
    from libs.shared.service_template import (
        DEFAULT_READINESS_CHECK_TIMEOUT_SECONDS,
        DEFAULT_SERVICE_TEMPLATE_PUBLIC_PATHS,
        PLATFORM_TENANT_ID,
        PublicPathTenantContextMiddleware,
        ReadinessCheck,
        ReadinessCheckRegistry,
        ReadinessCheckResult,
        ReadinessReport,
        ServiceTemplateConfig,
        ServiceTemplateState,
        create_service_app,
    )
    from libs.shared.tenant import (
        InMemoryAuditSink,
        TenantAuditEvent,
        TenantContext,
        TenantContextASGIMiddleware,
        TenantCoreError,
        TenantIsolationError,
        TenantScopedRepository,
        UnauthorizedError,
        assert_requested_tenant,
        decode_hs256_jwt,
        encode_hs256_jwt,
        get_tenant_context,
        require_tenant_context,
        reset_tenant_context,
        set_tenant_context,
        tenant_context_from_authorization_header,
        tenant_context_from_claims,
        tenant_context_from_trusted_headers,
        tenant_context_scope,
        tenant_headers_from_context,
    )
    from libs.shared.tenant_marketplace import (
        InMemoryTenantMarketplace,
        TenantMarketplaceApplication,
        TenantMarketplaceApplicationStatus,
        TenantMarketplaceDecision,
        TenantMarketplaceModerationRecord,
        TenantMarketplaceProfile,
        TenantMarketplaceProfileStatus,
        TenantMarketplaceProvisioningResult,
        TenantMarketplaceSubmission,
    )
    from libs.shared.tenant_resources import (
        InMemoryTenantResourceManager,
        TenantResourceDecision,
        TenantResourceLimitError,
        TenantResourceManager,
        TenantResourcePlan,
        TenantResourceSnapshot,
    )
    from libs.shared.testing import (
        DEFAULT_TEST_JWT_SECRET,
        DEFAULT_TEST_NOW,
        TenantTestDataset,
        TenantTestIdentity,
        assert_only_tenant_records,
        build_tenant_test_dataset,
    )
    from libs.shared.vector import (
        CHROMA_HOST_ENV,
        CHROMA_PORT_ENV,
        CHROMA_SSL_ENV,
        DEFAULT_CHROMA_COLLECTION_PREFIX,
        DEFAULT_CHROMA_ENVIRONMENT,
        DEFAULT_CHROMA_PORT,
        ChromaSettings,
        ChromaTenantVectorStore,
        InMemoryTenantVectorStore,
        MetadataScalar,
        TenantVectorStore,
        VectorMetadata,
        VectorRecord,
        VectorSearchResult,
        build_tenant_vector_collection_name,
        chroma_host_from_env,
        chroma_port_from_env,
        chroma_ssl_from_env,
        validate_chroma_host,
        validate_chroma_port,
    )


_EXPORTS: dict[str, str] = {
    "AUDIT_HASH_ALGORITHM": "libs.shared.audit_logger",
    "AUDIT_HASH_PATTERN_TEXT": "libs.shared.models",
    "AUDIENCE_ROLE": "libs.shared.rbac",
    "APIGatewayASGIMiddleware": "libs.shared.gateway",
    "APP_SETTINGS_ENV_NAMES": "libs.shared.config",
    "AddSession": "libs.shared.db",
    "AppSettings": "libs.shared.config",
    "AuditHash": "libs.shared.models",
    "AuditHashReference": "libs.shared.models",
    "AuditLogRecord": "libs.shared.audit_logger",
    "AuditLogSink": "libs.shared.audit_logger",
    "AuditLogger": "libs.shared.audit_logger",
    "AuditPayload": "libs.shared.audit_logger",
    "AuthTokenService": "libs.shared.auth",
    "AuthMethod": "libs.shared.s2s_auth",
    "AccessPolicy": "libs.shared.rbac",
    "AsyncDatabase": "libs.shared.db",
    "AsyncScalarSession": "libs.shared.db",
    "Base": "libs.shared.db",
    "BLOCKCHAIN_AUDIT_ENDPOINT_POLICIES": "libs.shared.rbac",
    "BOARD_ROLE": "libs.shared.rbac",
    "BASE_APP_LOG_LEVELS": "libs.shared.server",
    "BASE_APP_SYSTEM_PUBLIC_PATHS": "libs.shared.server",
    "BaseAppConfig": "libs.shared.server",
    "BaseAppState": "libs.shared.server",
    "CHROMA_HOST_ENV": "libs.shared.vector",
    "CHROMA_PORT_ENV": "libs.shared.vector",
    "CHROMA_SSL_ENV": "libs.shared.vector",
    "COUNCIL_ROLE": "libs.shared.rbac",
    "CorrelationId": "libs.shared.models",
    "DATABASE_URL_ENV": "libs.shared.db",
    "DEFAULT_CHROMA_COLLECTION_PREFIX": "libs.shared.vector",
    "DEFAULT_CHROMA_ENVIRONMENT": "libs.shared.vector",
    "DEFAULT_CHROMA_PORT": "libs.shared.vector",
    "DEFAULT_COMMANDS_EXCHANGE": "libs.shared.events",
    "DEFAULT_DEAD_LETTER_EXCHANGE": "libs.shared.events",
    "DEFAULT_EVENTS_EXCHANGE": "libs.shared.events",
    "DEFAULT_BASE_APP_DOCS_URL": "libs.shared.server",
    "DEFAULT_BASE_APP_LOG_LEVEL": "libs.shared.server",
    "DEFAULT_BASE_APP_OPENAPI_URL": "libs.shared.server",
    "DEFAULT_BASE_APP_PORT": "libs.shared.server",
    "DEFAULT_BASE_APP_REDOC_URL": "libs.shared.server",
    "DEFAULT_BUILD_INFO_PATH": "libs.shared.server",
    "DEFAULT_RUNTIME_APP_HOST": "libs.shared.server",
    "DEFAULT_METRICS_PATH": "libs.shared.observability",
    "DEFAULT_PRESIGNED_EXPIRES_SECONDS": "libs.shared.object_storage",
    "DEFAULT_READINESS_CHECK_TIMEOUT_SECONDS": "libs.shared.service_template",
    "DEFAULT_S3_REGION": "libs.shared.object_storage",
    "DEFAULT_S3_TENANT_PREFIX": "libs.shared.object_storage",
    "DEFAULT_SERVICE_TEMPLATE_PUBLIC_PATHS": "libs.shared.service_template",
    "DEFAULT_S2S_REPLAY_WINDOW_SECONDS": "libs.shared.s2s_auth",
    "DEFAULT_TEST_JWT_SECRET": "libs.shared.testing",
    "DEFAULT_TEST_NOW": "libs.shared.testing",
    "CacheSettings": "libs.shared.cache",
    "ChromaSettings": "libs.shared.vector",
    "ChromaTenantVectorStore": "libs.shared.vector",
    "CircuitBreakerPolicy": "libs.shared.resilience",
    "CircuitBreakerSnapshot": "libs.shared.resilience",
    "CircuitBreakerState": "libs.shared.resilience",
    "Contribution": "libs.shared.db",
    "DatabaseSettings": "libs.shared.db",
    "DependencyCallResult": "libs.shared.resilience",
    "DependencyCallStatus": "libs.shared.resilience",
    "DependencyFailure": "libs.shared.resilience",
    "DependencyKind": "libs.shared.resilience",
    "DependencyResilienceGuard": "libs.shared.resilience",
    "EndpointAccessPolicy": "libs.shared.rbac",
    "EnvSecretProvider": "libs.shared.config",
    "ErrorBody": "libs.shared.errors",
    "ErrorCode": "libs.shared.errors",
    "ErrorEnvelope": "libs.shared.errors",
    "EVENT_TYPE_PATTERN_TEXT": "libs.shared.models",
    "EventType": "libs.shared.models",
    "EventEnvelope": "libs.shared.events",
    "EventIdempotencyStore": "libs.shared.events",
    "EventPublisher": "libs.shared.events",
    "FailureMode": "libs.shared.resilience",
    "FORBIDDEN_CODE": "libs.shared.rbac",
    "ForbiddenError": "libs.shared.rbac",
    "GOVERNANCE_ROLES": "libs.shared.rbac",
    "GatewayRoute": "libs.shared.gateway",
    "GatewayRouteNotFoundError": "libs.shared.gateway",
    "IDEMPOTENCY_CONFLICT_CODE": "libs.shared.errors",
    "IdempotencyKey": "libs.shared.models",
    "IdempotentEventProcessor": "libs.shared.events",
    "InMemoryAuditSink": "libs.shared.tenant",
    "InMemoryAuditLogSink": "libs.shared.audit_logger",
    "InMemoryEventBus": "libs.shared.events",
    "InMemoryEventIdempotencyStore": "libs.shared.events",
    "InMemoryRateLimiter": "libs.shared.gateway",
    "InMemoryRefreshTokenStore": "libs.shared.auth",
    "InMemoryS2SReplayCache": "libs.shared.s2s_auth",
    "InMemoryTenantCache": "libs.shared.cache",
    "InMemoryTenantMarketplace": "libs.shared.tenant_marketplace",
    "InMemoryTenantObjectStorage": "libs.shared.object_storage",
    "InMemoryTenantResourceManager": "libs.shared.tenant_resources",
    "InMemoryTenantVectorStore": "libs.shared.vector",
    "JsonLogFormatter": "libs.shared.logging_config",
    "JSONValue": "libs.shared.models",
    "K8sS2SAuth": "libs.shared.s2s_auth",
    "K8sTokenReviewResult": "libs.shared.s2s_auth",
    "AsyncLoadOperation": "libs.shared.load_testing",
    "LoadOperation": "libs.shared.load_testing",
    "LoadScenarioResult": "libs.shared.load_testing",
    "LoadTarget": "libs.shared.load_testing",
    "LoadTargetEvaluation": "libs.shared.load_testing",
    "LoadTestReport": "libs.shared.load_testing",
    "MEMBER_ASSOC_ROLE": "libs.shared.rbac",
    "MEMBER_FULL_ROLE": "libs.shared.rbac",
    "MetadataScalar": "libs.shared.vector",
    "NAMING_CONVENTION": "libs.shared.db",
    "ObjectMetadata": "libs.shared.object_storage",
    "OIDCK8sTokenValidator": "libs.shared.s2s_auth",
    "OPERATION_COUNTER": "libs.shared.observability",
    "OPERATION_DURATION": "libs.shared.observability",
    "ObservabilityContext": "libs.shared.observability",
    "ObservabilityPrivacyError": "libs.shared.observability",
    "PayoutDistribution": "libs.shared.db",
    "POSTGRESQL_ASYNCPG_DRIVER": "libs.shared.db",
    "POLICY_GATE_REQUIRED_CODE": "libs.shared.errors",
    "PRESIDIUM_ROLE": "libs.shared.rbac",
    "PLATFORM_TENANT_ID": "libs.shared.service_template",
    "PageMeta": "libs.shared.models",
    "PagedResponse": "libs.shared.models",
    "PaginationParams": "libs.shared.models",
    "PublishedEvent": "libs.shared.events",
    "PublicPathTenantContextMiddleware": "libs.shared.service_template",
    "RABBITMQ_URL_ENV": "libs.shared.events",
    "RBACASGIMiddleware": "libs.shared.rbac",
    "RSAS2SAuth": "libs.shared.s2s_auth",
    "REDIS_URL_ENV": "libs.shared.cache",
    "REDACTED_SECRET": "libs.shared.config",
    "RabbitMQEventBus": "libs.shared.events",
    "RabbitMQSettings": "libs.shared.events",
    "ReadinessCheck": "libs.shared.service_template",
    "ReadinessCheckRegistry": "libs.shared.service_template",
    "ReadinessCheckResult": "libs.shared.service_template",
    "ReadinessReport": "libs.shared.service_template",
    "RateLimitDecision": "libs.shared.gateway",
    "RateLimitedError": "libs.shared.gateway",
    "RateLimiter": "libs.shared.gateway",
    "RateLimitPolicy": "libs.shared.gateway",
    "RATE_LIMITED_CODE": "libs.shared.errors",
    "RefreshTokenRecord": "libs.shared.auth",
    "RefreshTokenStore": "libs.shared.auth",
    "RequestContextModel": "libs.shared.models",
    "RedisTenantCache": "libs.shared.cache",
    "RoleName": "libs.shared.models",
    "RetryPolicy": "libs.shared.resilience",
    "S2SAuthenticationError": "libs.shared.s2s_auth",
    "S2SAuthenticator": "libs.shared.s2s_auth",
    "S2SConfig": "libs.shared.s2s_auth",
    "S2SIdentity": "libs.shared.s2s_auth",
    "S2S_SHARED_SECRET_ENV": "libs.shared.s2s_auth",
    "S3_ACCESS_KEY_ENV": "libs.shared.object_storage",
    "S3_BUCKET_ENV": "libs.shared.object_storage",
    "S3_ENDPOINT_URL_ENV": "libs.shared.object_storage",
    "S3_REGION_ENV": "libs.shared.object_storage",
    "S3_SECRET_KEY_ENV": "libs.shared.object_storage",
    "S3Settings": "libs.shared.object_storage",
    "S3TenantObjectStorage": "libs.shared.object_storage",
    "ScalarRows": "libs.shared.db",
    "SECRET_ENV_NAMES": "libs.shared.config",
    "SERVICE_NOT_FOUND_CODE": "libs.shared.errors",
    "SecretProvider": "libs.shared.config",
    "ServiceTemplateConfig": "libs.shared.service_template",
    "ServiceTemplateState": "libs.shared.service_template",
    "SharedBaseModel": "libs.shared.models",
    "SharedError": "libs.shared.errors",
    "SharedSecretS2SAuth": "libs.shared.s2s_auth",
    "SubjectId": "libs.shared.models",
    "TOTPService": "libs.shared.auth",
    "TENANT_ID_PATTERN_TEXT": "libs.shared.models",
    "TENANT_ISOLATION_CODE": "libs.shared.errors",
    "TOKEN_PATTERN_TEXT": "libs.shared.models",
    "TimeoutBudget": "libs.shared.resilience",
    "TenantCache": "libs.shared.cache",
    "Tenant": "libs.shared.db",
    "TenantAuditEvent": "libs.shared.tenant",
    "TenantContext": "libs.shared.tenant",
    "TenantContextASGIMiddleware": "libs.shared.tenant",
    "TenantCoreError": "libs.shared.tenant",
    "TenantTestDataset": "libs.shared.testing",
    "TenantTestIdentity": "libs.shared.testing",
    "TenantIsolationError": "libs.shared.tenant",
    "TokenReviewK8sTokenValidator": "libs.shared.s2s_auth",
    "TenantMarketplaceApplication": "libs.shared.tenant_marketplace",
    "TenantMarketplaceApplicationStatus": "libs.shared.tenant_marketplace",
    "TenantMarketplaceDecision": "libs.shared.tenant_marketplace",
    "TenantMarketplaceModerationRecord": "libs.shared.tenant_marketplace",
    "TenantMarketplaceProfile": "libs.shared.tenant_marketplace",
    "TenantMarketplaceProfileStatus": "libs.shared.tenant_marketplace",
    "TenantMarketplaceProvisioningResult": "libs.shared.tenant_marketplace",
    "TenantMarketplaceSubmission": "libs.shared.tenant_marketplace",
    "TenantMetricRegistry": "libs.shared.observability",
    "TenantObject": "libs.shared.object_storage",
    "TenantObjectReference": "libs.shared.object_storage",
    "TenantObjectStorage": "libs.shared.object_storage",
    "TenantOwnedMixin": "libs.shared.db",
    "TenantScopedRepository": "libs.shared.tenant",
    "TenantScopedSQLAlchemyRepository": "libs.shared.db",
    "TenantScopedModel": "libs.shared.models",
    "TenantResourceDecision": "libs.shared.tenant_resources",
    "TenantResourceLimitError": "libs.shared.tenant_resources",
    "TenantResourceManager": "libs.shared.tenant_resources",
    "TenantResourcePlan": "libs.shared.tenant_resources",
    "TenantResourceSnapshot": "libs.shared.tenant_resources",
    "TenantId": "libs.shared.models",
    "TenantSetting": "libs.shared.db",
    "TenantSpan": "libs.shared.observability",
    "TenantTracer": "libs.shared.observability",
    "TenantVectorStore": "libs.shared.vector",
    "TenantWeight": "libs.shared.db",
    "TokenPair": "libs.shared.auth",
    "TraceContext": "libs.shared.observability",
    "TwoFactorConfirmation": "libs.shared.auth",
    "UNAUTHORIZED_CODE": "libs.shared.errors",
    "UnauthorizedError": "libs.shared.tenant",
    "VAULT_ENV_NAMES": "libs.shared.config",
    "VALIDATION_ERROR_CODE": "libs.shared.errors",
    "VectorMetadata": "libs.shared.vector",
    "VectorRecord": "libs.shared.vector",
    "VectorSearchResult": "libs.shared.vector",
    "WalletOperation": "libs.shared.db",
    "assert_requested_tenant": "libs.shared.tenant",
    "assert_only_tenant_records": "libs.shared.testing",
    "audit_hash": "libs.shared.audit_logger",
    "audit_hash_from_payload": "libs.shared.audit_logger",
    "build_audit_payload": "libs.shared.audit_logger",
    "build_runtime_app_host": "libs.shared.server",
    "build_runtime_base_app_config": "libs.shared.server",
    "canonical_audit_json": "libs.shared.audit_logger",
    "build_tenant_cache_key": "libs.shared.cache",
    "build_tenant_object_key": "libs.shared.object_storage",
    "build_tenant_object_prefix": "libs.shared.object_storage",
    "build_tenant_s3_prefix_policy": "libs.shared.object_storage",
    "build_tenant_test_dataset": "libs.shared.testing",
    "build_tenant_vector_collection_name": "libs.shared.vector",
    "build_structured_log_entry": "libs.shared.observability",
    "chroma_host_from_env": "libs.shared.vector",
    "chroma_port_from_env": "libs.shared.vector",
    "chroma_ssl_from_env": "libs.shared.vector",
    "constant_fallback": "libs.shared.resilience",
    "create_async_engine_from_url": "libs.shared.db",
    "create_async_session_factory": "libs.shared.db",
    "create_base_app": "libs.shared.server",
    "create_service_runtime_app": "libs.shared.server",
    "create_service_app": "libs.shared.service_template",
    "database_url_from_env": "libs.shared.db",
    "decode_hs256_jwt": "libs.shared.tenant",
    "detect_auth_method": "libs.shared.s2s_auth",
    "encode_hs256_jwt": "libs.shared.tenant",
    "error_response_body": "libs.shared.errors",
    "event_routing_key": "libs.shared.events",
    "evaluate_load_target": "libs.shared.load_testing",
    "format_structured_log": "libs.shared.observability",
    "get_tenant_context": "libs.shared.tenant",
    "get_s2s_auth": "libs.shared.s2s_auth",
    "hash_refresh_token": "libs.shared.auth",
    "load_app_settings": "libs.shared.config",
    "normalize_log_level": "libs.shared.logging_config",
    "observability_context_from_tenant_context": "libs.shared.observability",
    "rabbitmq_url_from_env": "libs.shared.events",
    "require_s2s": "libs.shared.s2s_auth",
    "require_access": "libs.shared.rbac",
    "require_any_role": "libs.shared.rbac",
    "require_tenant_context": "libs.shared.tenant",
    "reset_tenant_context": "libs.shared.tenant",
    "redis_url_from_env": "libs.shared.cache",
    "run_async_and_evaluate_load_scenario": "libs.shared.load_testing",
    "run_async_load_scenario": "libs.shared.load_testing",
    "run_and_evaluate_load_scenario": "libs.shared.load_testing",
    "run_load_scenario": "libs.shared.load_testing",
    "run_threaded_and_evaluate_load_scenario": "libs.shared.load_testing",
    "run_threaded_load_scenario": "libs.shared.load_testing",
    "s3_endpoint_url_from_env": "libs.shared.object_storage",
    "sanitize_observability_payload": "libs.shared.observability",
    "set_tenant_context": "libs.shared.tenant",
    "setup_logging": "libs.shared.logging_config",
    "tenant_context_from_authorization_header": "libs.shared.tenant",
    "tenant_context_from_claims": "libs.shared.tenant",
    "tenant_context_from_trusted_headers": "libs.shared.tenant",
    "tenant_context_scope": "libs.shared.tenant",
    "tenant_headers_from_context": "libs.shared.tenant",
    "topic_matches": "libs.shared.events",
    "validate_chroma_host": "libs.shared.vector",
    "validate_chroma_port": "libs.shared.vector",
    "validate_database_url": "libs.shared.db",
    "validate_rabbitmq_url": "libs.shared.events",
    "validate_redis_url": "libs.shared.cache",
    "validate_s3_bucket_name": "libs.shared.object_storage",
    "validate_s3_endpoint_url": "libs.shared.object_storage",
    "VaultSecretProvider": "libs.shared.config",
    "VaultSettings": "libs.shared.config",
}


def __getattr__(name: str) -> Any:
    try:
        module_name = _EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc

    module = import_module(module_name)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))


__all__ = [
    "AUDIT_HASH_ALGORITHM",
    "AUDIT_HASH_PATTERN_TEXT",
    "AUDIENCE_ROLE",
    "APIGatewayASGIMiddleware",
    "APP_SETTINGS_ENV_NAMES",
    "AddSession",
    "AppSettings",
    "AuditHash",
    "AuditHashReference",
    "AuditLogRecord",
    "AuditLogSink",
    "AuditLogger",
    "AuditPayload",
    "AuthTokenService",
    "AuthMethod",
    "AccessPolicy",
    "AsyncDatabase",
    "AsyncScalarSession",
    "Base",
    "BLOCKCHAIN_AUDIT_ENDPOINT_POLICIES",
    "BOARD_ROLE",
    "BASE_APP_LOG_LEVELS",
    "BASE_APP_SYSTEM_PUBLIC_PATHS",
    "BaseAppConfig",
    "BaseAppState",
    "CHROMA_HOST_ENV",
    "CHROMA_PORT_ENV",
    "CHROMA_SSL_ENV",
    "COUNCIL_ROLE",
    "CorrelationId",
    "DATABASE_URL_ENV",
    "DEFAULT_CHROMA_COLLECTION_PREFIX",
    "DEFAULT_CHROMA_ENVIRONMENT",
    "DEFAULT_CHROMA_PORT",
    "DEFAULT_COMMANDS_EXCHANGE",
    "DEFAULT_DEAD_LETTER_EXCHANGE",
    "DEFAULT_EVENTS_EXCHANGE",
    "DEFAULT_BASE_APP_DOCS_URL",
    "DEFAULT_BASE_APP_LOG_LEVEL",
    "DEFAULT_BASE_APP_OPENAPI_URL",
    "DEFAULT_BASE_APP_PORT",
    "DEFAULT_BASE_APP_REDOC_URL",
    "DEFAULT_BUILD_INFO_PATH",
    "DEFAULT_RUNTIME_APP_HOST",
    "DEFAULT_METRICS_PATH",
    "DEFAULT_PRESIGNED_EXPIRES_SECONDS",
    "DEFAULT_READINESS_CHECK_TIMEOUT_SECONDS",
    "DEFAULT_S3_REGION",
    "DEFAULT_S3_TENANT_PREFIX",
    "DEFAULT_SERVICE_TEMPLATE_PUBLIC_PATHS",
    "DEFAULT_S2S_REPLAY_WINDOW_SECONDS",
    "DEFAULT_TEST_JWT_SECRET",
    "DEFAULT_TEST_NOW",
    "CacheSettings",
    "ChromaSettings",
    "ChromaTenantVectorStore",
    "CircuitBreakerPolicy",
    "CircuitBreakerSnapshot",
    "CircuitBreakerState",
    "Contribution",
    "DatabaseSettings",
    "DependencyCallResult",
    "DependencyCallStatus",
    "DependencyFailure",
    "DependencyKind",
    "DependencyResilienceGuard",
    "EndpointAccessPolicy",
    "EnvSecretProvider",
    "ErrorBody",
    "ErrorCode",
    "ErrorEnvelope",
    "EVENT_TYPE_PATTERN_TEXT",
    "EventType",
    "EventEnvelope",
    "EventIdempotencyStore",
    "EventPublisher",
    "FailureMode",
    "FORBIDDEN_CODE",
    "ForbiddenError",
    "GOVERNANCE_ROLES",
    "GatewayRoute",
    "GatewayRouteNotFoundError",
    "IDEMPOTENCY_CONFLICT_CODE",
    "IdempotencyKey",
    "IdempotentEventProcessor",
    "InMemoryAuditSink",
    "InMemoryAuditLogSink",
    "InMemoryEventBus",
    "InMemoryEventIdempotencyStore",
    "InMemoryRateLimiter",
    "InMemoryRefreshTokenStore",
    "InMemoryS2SReplayCache",
    "InMemoryTenantCache",
    "InMemoryTenantMarketplace",
    "InMemoryTenantObjectStorage",
    "InMemoryTenantResourceManager",
    "InMemoryTenantVectorStore",
    "JsonLogFormatter",
    "JSONValue",
    "K8sS2SAuth",
    "K8sTokenReviewResult",
    "AsyncLoadOperation",
    "LoadOperation",
    "LoadScenarioResult",
    "LoadTarget",
    "LoadTargetEvaluation",
    "LoadTestReport",
    "MEMBER_ASSOC_ROLE",
    "MEMBER_FULL_ROLE",
    "MetadataScalar",
    "NAMING_CONVENTION",
    "ObjectMetadata",
    "OIDCK8sTokenValidator",
    "OPERATION_COUNTER",
    "OPERATION_DURATION",
    "ObservabilityContext",
    "ObservabilityPrivacyError",
    "PayoutDistribution",
    "POSTGRESQL_ASYNCPG_DRIVER",
    "POLICY_GATE_REQUIRED_CODE",
    "PRESIDIUM_ROLE",
    "PLATFORM_TENANT_ID",
    "PageMeta",
    "PagedResponse",
    "PaginationParams",
    "PublishedEvent",
    "PublicPathTenantContextMiddleware",
    "RABBITMQ_URL_ENV",
    "RBACASGIMiddleware",
    "RSAS2SAuth",
    "REDIS_URL_ENV",
    "REDACTED_SECRET",
    "RabbitMQEventBus",
    "RabbitMQSettings",
    "ReadinessCheck",
    "ReadinessCheckRegistry",
    "ReadinessCheckResult",
    "ReadinessReport",
    "RateLimitDecision",
    "RateLimitedError",
    "RateLimiter",
    "RateLimitPolicy",
    "RATE_LIMITED_CODE",
    "RefreshTokenRecord",
    "RefreshTokenStore",
    "RequestContextModel",
    "RedisTenantCache",
    "RoleName",
    "RetryPolicy",
    "S2SAuthenticationError",
    "S2SAuthenticator",
    "S2SConfig",
    "S2SIdentity",
    "S2S_SHARED_SECRET_ENV",
    "S3_ACCESS_KEY_ENV",
    "S3_BUCKET_ENV",
    "S3_ENDPOINT_URL_ENV",
    "S3_REGION_ENV",
    "S3_SECRET_KEY_ENV",
    "S3Settings",
    "S3TenantObjectStorage",
    "ScalarRows",
    "SECRET_ENV_NAMES",
    "SERVICE_NOT_FOUND_CODE",
    "SecretProvider",
    "ServiceTemplateConfig",
    "ServiceTemplateState",
    "SharedBaseModel",
    "SharedError",
    "SharedSecretS2SAuth",
    "SubjectId",
    "TOTPService",
    "TENANT_ID_PATTERN_TEXT",
    "TENANT_ISOLATION_CODE",
    "TOKEN_PATTERN_TEXT",
    "TimeoutBudget",
    "TenantCache",
    "Tenant",
    "TenantAuditEvent",
    "TenantContext",
    "TenantContextASGIMiddleware",
    "TenantCoreError",
    "TenantTestDataset",
    "TenantTestIdentity",
    "TenantIsolationError",
    "TokenReviewK8sTokenValidator",
    "TenantMarketplaceApplication",
    "TenantMarketplaceApplicationStatus",
    "TenantMarketplaceDecision",
    "TenantMarketplaceModerationRecord",
    "TenantMarketplaceProfile",
    "TenantMarketplaceProfileStatus",
    "TenantMarketplaceProvisioningResult",
    "TenantMarketplaceSubmission",
    "TenantMetricRegistry",
    "TenantObject",
    "TenantObjectReference",
    "TenantObjectStorage",
    "TenantOwnedMixin",
    "TenantScopedRepository",
    "TenantScopedSQLAlchemyRepository",
    "TenantScopedModel",
    "TenantResourceDecision",
    "TenantResourceLimitError",
    "TenantResourceManager",
    "TenantResourcePlan",
    "TenantResourceSnapshot",
    "TenantId",
    "TenantSetting",
    "TenantSpan",
    "TenantTracer",
    "TenantVectorStore",
    "TenantWeight",
    "TokenPair",
    "TraceContext",
    "TwoFactorConfirmation",
    "UNAUTHORIZED_CODE",
    "UnauthorizedError",
    "VAULT_ENV_NAMES",
    "VALIDATION_ERROR_CODE",
    "VectorMetadata",
    "VectorRecord",
    "VectorSearchResult",
    "WalletOperation",
    "assert_requested_tenant",
    "assert_only_tenant_records",
    "audit_hash",
    "audit_hash_from_payload",
    "build_audit_payload",
    "build_runtime_app_host",
    "build_runtime_base_app_config",
    "canonical_audit_json",
    "build_tenant_cache_key",
    "build_tenant_object_key",
    "build_tenant_object_prefix",
    "build_tenant_s3_prefix_policy",
    "build_tenant_test_dataset",
    "build_tenant_vector_collection_name",
    "build_structured_log_entry",
    "chroma_host_from_env",
    "chroma_port_from_env",
    "chroma_ssl_from_env",
    "constant_fallback",
    "create_async_engine_from_url",
    "create_async_session_factory",
    "create_base_app",
    "create_service_runtime_app",
    "create_service_app",
    "database_url_from_env",
    "decode_hs256_jwt",
    "detect_auth_method",
    "encode_hs256_jwt",
    "error_response_body",
    "event_routing_key",
    "evaluate_load_target",
    "format_structured_log",
    "get_tenant_context",
    "get_s2s_auth",
    "hash_refresh_token",
    "load_app_settings",
    "normalize_log_level",
    "observability_context_from_tenant_context",
    "rabbitmq_url_from_env",
    "require_s2s",
    "require_access",
    "require_any_role",
    "require_tenant_context",
    "reset_tenant_context",
    "redis_url_from_env",
    "run_async_and_evaluate_load_scenario",
    "run_async_load_scenario",
    "run_and_evaluate_load_scenario",
    "run_load_scenario",
    "run_threaded_and_evaluate_load_scenario",
    "run_threaded_load_scenario",
    "s3_endpoint_url_from_env",
    "sanitize_observability_payload",
    "set_tenant_context",
    "setup_logging",
    "tenant_context_from_authorization_header",
    "tenant_context_from_claims",
    "tenant_context_from_trusted_headers",
    "tenant_context_scope",
    "tenant_headers_from_context",
    "topic_matches",
    "validate_chroma_host",
    "validate_chroma_port",
    "validate_database_url",
    "validate_rabbitmq_url",
    "validate_redis_url",
    "validate_s3_bucket_name",
    "validate_s3_endpoint_url",
    "VaultSecretProvider",
    "VaultSettings",
]
